#
# Website: http://gobetween.io
# Documentation: https://github.com/yyyar/gobetween/wiki/Configuration
#

# Logging configuration
[logging]
format = "text" # (optional) "text" | "json"
level = "info" # "debug" | "info" | "warn" | "error"
output = "stdout" # "stdout" | "stderr" | "/path/to/gobetween.log"

# Pprof profiler configuration
[profiler]
enabled = false

# REST API server configuration
[api]
enabled = false

# Metrics server configuration
[metrics]
enabled = false

#
## Acme (letsencrypt) configuration.
## Letsencrypt allows server obtain free TLS certificates automagically.
## See https://letsencrypt.org for details.
##
## Each server that requires acme certificates should have acme_hosts configured in tls section.
#
#[acme]                           # (optional)
#challenge = "http"               # (optional) http | sni | dns
#http_bind = "0.0.0.0:80"         # (optional) It is possible to bind to other port, but letsencrypt will send requests to http(80) anyway
#cache_dir = "/tmp"               # (optional) directory to put acme certificates

# [servers]

[servers.responder]
bind = ":80"
protocol = "tcp"

[servers.responder.discovery]
kind = "static"
static_list = [
  "198.18.1.101:8001 weight=50 priority=1",
  "198.18.1.102:8002 weight=50 priority=1",
]
